name: Release

on:
  workflow_dispatch:
    inputs:   
      release_tag:
        description: 'release tag'
        required: true
      release_title:
        description: 'release title'
        required: false
      release_notes:
        description: 'release notes'     
        required: false
        default: ''

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build go binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/cli-linux-amd64 ./cmd/cli
          GOOS=linux GOARCH=386 go build -o build/cli-linux-386 ./cmd/cli
          GOOS=darwin GOARCH=amd64 go build -o build/cli-darwin-amd64 ./cmd/cli
          GOOS=darwin GOARCH=arm64 go build -o build/cli-darwin-arm64 ./cmd/cli
          GOOS=windows GOARCH=amd64 go build -o build/cli-windows-amd64 ./cmd/cli
          
      - name: create release along with artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
          body: "${{ github.event.inputs.release_notes }}"
          token: ${{ secrets.PAT_TOKEN }}
          name: "${{ github.event.inputs.release_title }}"
          tag: ${{ github.event.inputs.release_tag }}
